server:
  port: 8084
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false